import type { DoctorProfile, SpecialtyKey } from "./types"

// ── Radiologists (Human-in-the-Loop reviewers) ───────────────────────────────

export const RADIOLOGIST_PROFILES: DoctorProfile[] = [
  {
    id: "RAD-001",
    name: "Dr. Nodira Yusupova",
    specialty: "RADIOLOGIST",
    title: "Bosh Radiolog",
    experience: 14,
    clinic: "Toshkent Ilmiy Tibbiyot Markazi",
    region: "Toshkent",
    phone: "+998 71 234 56 78",
    photoUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.9,
    casesHandled: 4210,
    bio: "Ko'krak qafasi radiologiyasi va AI-yordamchi diagnostika sohasida 14 yillik tajribaga ega mutaxassis. CheXNet modelini klinik ishga tatbiq etishda ishtirok etgan.",
    education: "Toshkent Tibbiyot Akademiyasi (2009), Radiologiya bo'yicha magistratura (2011)",
    gender: "F",
    available: true,
  },
  {
    id: "RAD-002",
    name: "Dr. Otabek Rahmatullayev",
    specialty: "RADIOLOGIST",
    title: "Katta Radiolog",
    experience: 9,
    clinic: "Samarqand Viloyat Tibbiyot Birлашmaси",
    region: "Samarqand",
    phone: "+998 66 231 44 21",
    photoUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.7,
    casesHandled: 2780,
    bio: "Pnevmoniya, sil va kardiomegaliya diagnostikasi sohasida ixtisoslashgan. DICOM tasvirlarni interpretatsiya qilishda yuqori kompetensiyali mutaxassis.",
    education: "Samarqand Davlat Tibbiyot Instituti (2014), Radiologiya rezidenturasi (2016)",
    gender: "M",
    available: true,
  },
  {
    id: "RAD-003",
    name: "Dr. Zulfiya Xolmatova",
    specialty: "RADIOLOGIST",
    title: "Radiolog-Konsultant",
    experience: 11,
    clinic: "Buxoro Xususiy Tibbiyot Klinikasi",
    region: "Buxoro",
    phone: "+998 65 222 33 44",
    photoUrl: "https://randomuser.me/api/portraits/women/67.jpg",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.8,
    casesHandled: 3540,
    bio: "Onkologik va yurak-tomir kasalliklari rentgen diagnostikasida 11 yillik tajriba. Teleradiologiya va masofaviy konsultatsiya bo'yicha mutaxassis.",
    education: "Toshkent Tibbiyot Akademiyasi (2012), Xalqaro Radiologiya Sertifikati (FRCR, 2018)",
    gender: "F",
    available: false,
  },
  {
    id: "RAD-004",
    name: "Dr. Mirzo Ashrapov",
    specialty: "RADIOLOGIST",
    title: "Radiolog",
    experience: 6,
    clinic: "Andijon Viloyat Shifoxonasi",
    region: "Andijon",
    phone: "+998 74 225 17 89",
    photoUrl: "https://randomuser.me/api/portraits/men/55.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.6,
    casesHandled: 1650,
    bio: "Yosh va istiqbolli mutaxassis. Ko'krak qafasi va o'pka patologiyalari aniqlashda ixtisoslashgan. AI-assistiv diagnostika tizimlarini o'rganishga katta qiziqish bildiradi.",
    education: "Toshkent Tibbiyot Akademiyasi (2017), Radiologiya rezidenturasi (2019)",
    gender: "M",
    available: true,
  },
]

// ── Specialist doctors (referral targets) ────────────────────────────────────

export const SPECIALIST_DOCTORS: DoctorProfile[] = [
  // PULMONOLOGIST × 3
  {
    id: "PUL-001",
    name: "Dr. Sardor Aliyev",
    specialty: "PULMONOLOGIST",
    title: "Bosh Pulmonolog",
    experience: 16,
    clinic: "Toshkent Respublika Ihtisoslashtirilgan Tibbiyot Markazi",
    region: "Toshkent",
    phone: "+998 71 256 34 12",
    photoUrl: "https://randomuser.me/api/portraits/men/41.jpg",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.9,
    casesHandled: 5200,
    bio: "Pnevmoniya, sil va COPD bo'yicha Respublika darajasidagi etakchi mutaxassis. 16 yillik klinik tajriba, 40+ ilmiy maqola muallifi.",
    education: "TTA (2007), O'pka kasalliklari doktori (2013)",
    gender: "M",
    available: true,
  },
  {
    id: "PUL-002",
    name: "Dr. Kamola Rasulova",
    specialty: "PULMONOLOGIST",
    title: "Pulmonolog-Ftiziatr",
    experience: 10,
    clinic: "Jizzax Viloyat Ko'p Tarmoqli Tibbiyot Markazi",
    region: "Jizzax",
    phone: "+998 72 226 18 45",
    photoUrl: "https://randomuser.me/api/portraits/women/53.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.8,
    casesHandled: 3100,
    bio: "Tuberkulyoz va o'pka infeksiyalari bo'yicha ixtisoslashgan. Jizzax viloyatida TB skrining dasturini muvaffaqiyatli olib bormoqda.",
    education: "Samarqand Tibbiyot Instituti (2013), Ftiziatriya rezidenturasi (2015)",
    gender: "F",
    available: true,
  },
  {
    id: "PUL-003",
    name: "Dr. Bahrom Yuldashev",
    specialty: "PULMONOLOGIST",
    title: "Pulmonolog",
    experience: 8,
    clinic: "Namangan Viloyat Shifoxonasi",
    region: "Namangan",
    phone: "+998 69 234 55 67",
    photoUrl: "https://randomuser.me/api/portraits/men/7.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.7,
    casesHandled: 2400,
    bio: "COVID-19 va viral pnevmoniya bilan bog'liq o'pka asoratlarini davolashda katta tajribaga ega. Intensiv terapiya bo'limida ham ishlaydigan mutaxassis.",
    education: "Toshkent Tibbiyot Akademiyasi (2015), Pulmonologiya sertifikati (2017)",
    gender: "M",
    available: true,
  },

  // CARDIOLOGIST × 2
  {
    id: "CAR-001",
    name: "Dr. Bekzod Karimov",
    specialty: "CARDIOLOGIST",
    title: "Bosh Kardiolog",
    experience: 18,
    clinic: "Toshkent Shahri Kardiologiya Markazi",
    region: "Toshkent",
    phone: "+998 71 267 89 23",
    photoUrl: "https://randomuser.me/api/portraits/men/23.jpg",
    languages: ["O'zbek", "Rus", "Ingliz", "Nemis"],
    rating: 5.0,
    casesHandled: 6800,
    bio: "Respublika Bosh Kardiologlari kollegiyasi a'zosi. Kardiomegaliya, yurak etishmovchiligi va aritmiyadа etakchi mutaxassis. Yevropa Kardiologiya Jamiyati a'zosi.",
    education: "TTA (2005), Kardiologiya doktori (2010), Munich universitetida stajirovka (2014)",
    gender: "M",
    available: true,
  },
  {
    id: "CAR-002",
    name: "Dr. Dilnoza Ismoilova",
    specialty: "CARDIOLOGIST",
    title: "Kardiolog-Eхokardiograf",
    experience: 11,
    clinic: "Samarqand Ko'p Tarmoqli Ixtisoslashtirilgan Klinik Shifoxona",
    region: "Samarqand",
    phone: "+998 66 233 44 55",
    photoUrl: "https://randomuser.me/api/portraits/women/31.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.8,
    casesHandled: 3700,
    bio: "EхoKG diagnostikasi va yurak-qon tomir kasalliklarini davolashda ixtisoslashgan. Kardiomegaliyani erkaklay aniqlash bo'yicha ko'p yillik tajribali mutaxassis.",
    education: "Samarqand Davlat Tibbiyot Instituti (2012), Kardiologiya rezidenturasi (2014)",
    gender: "F",
    available: false,
  },

  // ORTHOPEDIC × 2
  {
    id: "ORT-001",
    name: "Dr. Jasur To'rayev",
    specialty: "ORTHOPEDIC",
    title: "Ortoped-Travmatolog",
    experience: 13,
    clinic: "Toshkent Ortopediya va Travmatologiya Instituti",
    region: "Toshkent",
    phone: "+998 71 244 66 77",
    photoUrl: "https://randomuser.me/api/portraits/men/46.jpg",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.8,
    casesHandled: 4100,
    bio: "Ko'krak qafasi suyaklari sinishi, umurtqa va qovurg'a kasalliklarida katta tajriba. Minimal invaziv jarrohlik usullari bo'yicha sertifikat.",
    education: "Toshkent Tibbiyot Akademiyasi (2010), Ortopediya doktori (2015), AO Foundation kurs (2019)",
    gender: "M",
    available: true,
  },
  {
    id: "ORT-002",
    name: "Dr. Aziza Qodirova",
    specialty: "ORTHOPEDIC",
    title: "Ortoped",
    experience: 8,
    clinic: "Farg'ona Viloyat Ortopediya Markazi",
    region: "Farg'ona",
    phone: "+998 73 244 77 88",
    photoUrl: "https://randomuser.me/api/portraits/women/27.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.7,
    casesHandled: 2200,
    bio: "Suyak sinishlari va ortopedik deformatsiyalarni davolashda ixtisoslashgan. Yosh bemorlarda revmatoid artrit diagnostikasida ham tajribali.",
    education: "Farg'ona Tibbiyot Instituti (2015), Ortopediya rezidenturasi (2017)",
    gender: "F",
    available: true,
  },

  // ONCOLOGIST × 2
  {
    id: "ONC-001",
    name: "Dr. Rustam Egamov",
    specialty: "ONCOLOGIST",
    title: "Onkolog / Torakal Jarroh",
    experience: 20,
    clinic: "Toshkent Onkologiya Respublika Ixtisoslashtirilgan Ilmiy-Amaliy Tibbiyot Markazi",
    region: "Toshkent",
    phone: "+998 71 278 90 11",
    photoUrl: "https://randomuser.me/api/portraits/men/38.jpg",
    languages: ["O'zbek", "Rus", "Ingliz"],
    rating: 4.9,
    casesHandled: 7200,
    bio: "O'pka va ko'krak qafasi onkologiyasi bo'yicha Respublika etakchi mutaxassisi. 20 yillik tajriba, 80+ ilmiy maqola. Xalqaro onkologiya konferensiyalari ishtirokchisi.",
    education: "TTA (2003), Onkologiya doktori (2009), MD Anderson Cancer Center (2015)",
    gender: "M",
    available: true,
  },
  {
    id: "ONC-002",
    name: "Dr. Malika Sattorova",
    specialty: "ONCOLOGIST",
    title: "Onkolog",
    experience: 12,
    clinic: "Qashqadaryo Viloyat Onkologiya Dispanseri",
    region: "Qashqadaryo",
    phone: "+998 75 255 33 22",
    photoUrl: "https://randomuser.me/api/portraits/women/59.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.8,
    casesHandled: 3900,
    bio: "O'pka nodullari va massalarini erta aniqlash hamda davolashda ixtisoslashgan. Kemoterapiya va radioterapiya bo'yicha tajribali mutaxassis.",
    education: "Samarqand Tibbiyot Instituti (2011), Onkologiya rezidenturasi (2013)",
    gender: "F",
    available: true,
  },

  // GENERAL × 3
  {
    id: "GEN-001",
    name: "Dr. Oybek Nazarov",
    specialty: "GENERAL",
    title: "Oilaviy Shifokor",
    experience: 7,
    clinic: "Toshkent Shahar №3 Oilaviy Poliklinikasi",
    region: "Toshkent",
    phone: "+998 71 291 23 45",
    photoUrl: "https://randomuser.me/api/portraits/men/18.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.6,
    casesHandled: 8500,
    bio: "Umumiy amaliyot shifokorian sifatida keng profilli tajribaga ega. Profilaktika, patronaj va surunkali kasalliklarni boshqarish sohasida ixtisoslashgan.",
    education: "Toshkent Tibbiyot Akademiyasi (2016), Umumiy amaliyot sertifikati (2018)",
    gender: "M",
    available: true,
  },
  {
    id: "GEN-002",
    name: "Dr. Zilola Umarova",
    specialty: "GENERAL",
    title: "Oilaviy Shifokor",
    experience: 9,
    clinic: "Jizzax Rayon №1 Poliklinikasi",
    region: "Jizzax",
    phone: "+998 72 222 11 33",
    photoUrl: "https://randomuser.me/api/portraits/women/73.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.7,
    casesHandled: 11200,
    bio: "Jizzax shahrida patronaj xizmati va profilaktik skrining dasturlarini olib boruvchi tajribali oilaviy shifokor.",
    education: "Samarqand Tibbiyot Instituti (2014), Oilaviy tibbiyot sertifikati (2016)",
    gender: "F",
    available: true,
  },
  {
    id: "GEN-003",
    name: "Dr. Humoyun Mirzayev",
    specialty: "GENERAL",
    title: "Umumiy Amaliyot Shifokori",
    experience: 5,
    clinic: "Namangan Shahar №5 Poliklinikasi",
    region: "Namangan",
    phone: "+998 69 251 88 99",
    photoUrl: "https://randomuser.me/api/portraits/men/62.jpg",
    languages: ["O'zbek", "Rus"],
    rating: 4.5,
    casesHandled: 4300,
    bio: "Yosh va energik shifokor. Profilaktika va salomatlikni saqlash bo'yicha zamonaviy yondashuvlar tarafdori.",
    education: "Namangan Tibbiyot Instituti (2018), Umumiy amaliyot sertifikati (2020)",
    gender: "M",
    available: true,
  },
]

// ── Helpers ───────────────────────────────────────────────────────────────────

export function getSpecialistsForSpecialty(key: SpecialtyKey): DoctorProfile[] {
  return SPECIALIST_DOCTORS.filter((d) => d.specialty === key)
}

export function pickSpecialistDoctor(key: SpecialtyKey, seed: number): DoctorProfile {
  const pool = getSpecialistsForSpecialty(key)
  return pool[seed % pool.length]
}

export function getRadiologistById(id: string): DoctorProfile | undefined {
  return RADIOLOGIST_PROFILES.find((r) => r.id === id)
}
